# fly.db.prod.toml app configuration file for pax-tt-db-prod

app = "pax-tt-db-prod"
primary_region = "iad"

[build]
  image = "postgres:18.3"

[mounts]
  source = "pg_data_prod"
  destination = "/var/lib/postgresql"

[[services]]
  internal_port = 5432
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = []
    port = 5432

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

[[vm]]
  size = "shared-cpu-1x"
  memory = 1024

[[restart]]
  policy = "on-failure"
  retries = 3
