# fly.toml app configuration file generated for pax-tt-app on 2025-07-05T22:37:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pax-tt-app'
primary_region = 'iad'

[env]
  DATABASE_PATH = "/data/boardgames.db"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-4x'

[mounts]
  source = "boardgames_data"
  destination = "/data"

[[restart]]
  policy = "on-failure"
  retries = 3

[processes]
  app = "/app/start.sh"