"""remove user preference tables

Revision ID: 2ef6c56d7dc0
Revises: 69941843136f
Create Date: 2025-06-22 23:06:54.078550

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ef6c56d7dc0"
down_revision: Union[str, None] = "69941843136f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return table_name in set(inspector.get_table_names())


def index_exists(table_name: str, index_name: str) -> bool:
    if not table_exists(table_name):
        return False
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_index_names = {
        index["name"] for index in inspector.get_indexes(table_name)
    }
    return index_name in existing_index_names


def drop_index_if_exists(table_name: str, index_name: str) -> None:
    if index_exists(table_name, index_name):
        op.drop_index(index_name, table_name=table_name)


def drop_table_if_exists(table_name: str) -> None:
    if table_exists(table_name):
        op.drop_table(table_name)


def upgrade() -> None:
    """Upgrade schema."""
    drop_index_if_exists("user_disliked_games", op.f("ix_user_disliked_games_id"))
    drop_table_if_exists("user_disliked_games")
    drop_index_if_exists("user_liked_games", op.f("ix_user_liked_games_id"))
    drop_table_if_exists("user_liked_games")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_liked_games",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("game_id", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_liked_games_id"), "user_liked_games", ["id"], unique=False
    )
    op.create_table(
        "user_disliked_games",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("game_id", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_disliked_games_id"), "user_disliked_games", ["id"], unique=False
    )
    # ### end Alembic commands ###
