"""Add user_suggestions table

Revision ID: 594a7422f114
Revises: 6d4ea4dc16c2
Create Date: 2025-07-12 21:16:40.475282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594a7422f114'
down_revision: Union[str, None] = '6d4ea4dc16c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_artists_boardgameartist_id'), 'artists', ['boardgameartist_id'], unique=False)
    op.create_index(op.f('ix_artists_game_id'), 'artists', ['game_id'], unique=False)
    op.create_index(op.f('ix_categories_boardgamecategory_id'), 'categories', ['boardgamecategory_id'], unique=False)
    op.create_index(op.f('ix_categories_game_id'), 'categories', ['game_id'], unique=False)
    op.create_index(op.f('ix_designers_boardgamedesigner_id'), 'designers', ['boardgamedesigner_id'], unique=False)
    op.create_index(op.f('ix_designers_game_id'), 'designers', ['game_id'], unique=False)
    op.create_index(op.f('ix_games_abstracts_rank'), 'games', ['abstracts_rank'], unique=False)
    op.create_index(op.f('ix_games_cgs_rank'), 'games', ['cgs_rank'], unique=False)
    op.create_index(op.f('ix_games_childrens_games_rank'), 'games', ['childrens_games_rank'], unique=False)
    op.create_index(op.f('ix_games_family_games_rank'), 'games', ['family_games_rank'], unique=False)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_index(op.f('ix_games_party_games_rank'), 'games', ['party_games_rank'], unique=False)
    op.create_index(op.f('ix_games_strategy_games_rank'), 'games', ['strategy_games_rank'], unique=False)
    op.create_index(op.f('ix_games_thematic_rank'), 'games', ['thematic_rank'], unique=False)
    op.create_index(op.f('ix_games_wargames_rank'), 'games', ['wargames_rank'], unique=False)
    op.create_index(op.f('ix_mechanics_boardgamemechanic_id'), 'mechanics', ['boardgamemechanic_id'], unique=False)
    op.create_index(op.f('ix_mechanics_game_id'), 'mechanics', ['game_id'], unique=False)
    op.create_index(op.f('ix_pax_games_bgg_id'), 'pax_games', ['bgg_id'], unique=False)
    op.create_index(op.f('ix_publishers_game_id'), 'publishers', ['game_id'], unique=False)
    op.create_index(op.f('ix_suggested_players_game_id'), 'suggested_players', ['game_id'], unique=False)
    op.create_index(op.f('ix_suggested_players_player_count'), 'suggested_players', ['player_count'], unique=False)
    op.create_index(op.f('ix_suggested_players_recommendation_level'), 'suggested_players', ['recommendation_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggested_players_recommendation_level'), table_name='suggested_players')
    op.drop_index(op.f('ix_suggested_players_player_count'), table_name='suggested_players')
    op.drop_index(op.f('ix_suggested_players_game_id'), table_name='suggested_players')
    op.drop_index(op.f('ix_publishers_game_id'), table_name='publishers')
    op.drop_index(op.f('ix_pax_games_bgg_id'), table_name='pax_games')
    op.drop_index(op.f('ix_mechanics_game_id'), table_name='mechanics')
    op.drop_index(op.f('ix_mechanics_boardgamemechanic_id'), table_name='mechanics')
    op.drop_index(op.f('ix_games_wargames_rank'), table_name='games')
    op.drop_index(op.f('ix_games_thematic_rank'), table_name='games')
    op.drop_index(op.f('ix_games_strategy_games_rank'), table_name='games')
    op.drop_index(op.f('ix_games_party_games_rank'), table_name='games')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_family_games_rank'), table_name='games')
    op.drop_index(op.f('ix_games_childrens_games_rank'), table_name='games')
    op.drop_index(op.f('ix_games_cgs_rank'), table_name='games')
    op.drop_index(op.f('ix_games_abstracts_rank'), table_name='games')
    op.drop_index(op.f('ix_designers_game_id'), table_name='designers')
    op.drop_index(op.f('ix_designers_boardgamedesigner_id'), table_name='designers')
    op.drop_index(op.f('ix_categories_game_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_boardgamecategory_id'), table_name='categories')
    op.drop_index(op.f('ix_artists_game_id'), table_name='artists')
    op.drop_index(op.f('ix_artists_boardgameartist_id'), table_name='artists')
    # ### end Alembic commands ###
