"""add user auth tables

Revision ID: 69941843136f
Revises: 163d675a5e9d
Create Date: 2025-06-22 23:01:21.946626

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69941843136f"
down_revision: Union[str, None] = "163d675a5e9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def drop_index_if_exists(table_name: str, index_name: str) -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_index_names = {
        index["name"] for index in inspector.get_indexes(table_name)
    }
    if index_name in existing_index_names:
        op.drop_index(index_name, table_name=table_name)


def create_index_if_missing(
    table_name: str, index_name: str, columns: list[str], unique: bool = False
) -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_index_names = {
        index["name"] for index in inspector.get_indexes(table_name)
    }
    if index_name not in existing_index_names:
        op.create_index(index_name, table_name, columns, unique=unique)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    drop_index_if_exists("artists", op.f("idx_artists_boardgameartist_id"))
    drop_index_if_exists("artists", op.f("idx_artists_game_id"))
    drop_index_if_exists("categories", op.f("idx_categories_boardgamecategory_id"))
    drop_index_if_exists("categories", op.f("idx_categories_game_id"))
    drop_index_if_exists("designers", op.f("idx_designers_boardgamedesigner_id"))
    drop_index_if_exists("designers", op.f("idx_designers_game_id"))
    drop_index_if_exists("games", op.f("idx_games_abstracts_rank"))
    drop_index_if_exists("games", op.f("idx_games_average"))
    drop_index_if_exists("games", op.f("idx_games_average_weight"))
    drop_index_if_exists("games", op.f("idx_games_cgs_rank"))
    drop_index_if_exists("games", op.f("idx_games_childrens_games_rank"))
    drop_index_if_exists("games", op.f("idx_games_family_games_rank"))
    drop_index_if_exists("games", op.f("idx_games_max_players"))
    drop_index_if_exists("games", op.f("idx_games_min_players"))
    drop_index_if_exists("games", op.f("idx_games_name"))
    drop_index_if_exists("games", op.f("idx_games_party_games_rank"))
    drop_index_if_exists("games", op.f("idx_games_rank"))
    drop_index_if_exists("games", op.f("idx_games_strategy_games_rank"))
    drop_index_if_exists("games", op.f("idx_games_thematic_rank"))
    drop_index_if_exists("games", op.f("idx_games_wargames_rank"))
    drop_index_if_exists("games", op.f("idx_games_year_published"))
    drop_index_if_exists("mechanics", op.f("idx_mechanics_boardgamemechanic_id"))
    drop_index_if_exists("mechanics", op.f("idx_mechanics_game_id"))
    drop_index_if_exists("library_games", op.f("idx_library_games_bgg_id"))
    drop_index_if_exists("suggested_players", op.f("idx_suggested_players_game_id"))
    drop_index_if_exists(
        "suggested_players", op.f("idx_suggested_players_player_count")
    )
    drop_index_if_exists(
        "suggested_players", op.f("idx_suggested_players_recommendation_level")
    )
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    if "users" not in existing_tables:
        op.create_table(
            "users",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("username", sa.String(), nullable=True),
            sa.Column("email", sa.String(), nullable=True),
            sa.Column("hashed_password", sa.String(), nullable=True),
            sa.Column("is_active", sa.Boolean(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("username"),
        )
    create_index_if_missing("users", op.f("ix_users_id"), ["id"], unique=False)
    create_index_if_missing(
        "users", op.f("ix_users_username"), ["username"], unique=True
    )
    create_index_if_missing("users", op.f("ix_users_email"), ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.create_index(
        op.f("idx_suggested_players_recommendation_level"),
        "suggested_players",
        ["recommendation_level"],
        unique=False,
    )
    op.create_index(
        op.f("idx_suggested_players_player_count"),
        "suggested_players",
        ["player_count"],
        unique=False,
    )
    op.create_index(
        op.f("idx_suggested_players_game_id"),
        "suggested_players",
        ["game_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_library_games_bgg_id"), "library_games", ["bgg_id"], unique=False
    )
    op.create_index(
        op.f("idx_mechanics_game_id"), "mechanics", ["game_id"], unique=False
    )
    op.create_index(
        op.f("idx_mechanics_boardgamemechanic_id"),
        "mechanics",
        ["boardgamemechanic_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_games_year_published"), "games", ["year_published"], unique=False
    )
    op.create_index(
        op.f("idx_games_wargames_rank"), "games", ["wargames_rank"], unique=False
    )
    op.create_index(
        op.f("idx_games_thematic_rank"), "games", ["thematic_rank"], unique=False
    )
    op.create_index(
        op.f("idx_games_strategy_games_rank"),
        "games",
        ["strategy_games_rank"],
        unique=False,
    )
    op.create_index(op.f("idx_games_rank"), "games", ["rank"], unique=False)
    op.create_index(
        op.f("idx_games_party_games_rank"), "games", ["party_games_rank"], unique=False
    )
    op.create_index(op.f("idx_games_name"), "games", ["name"], unique=False)
    op.create_index(
        op.f("idx_games_min_players"), "games", ["min_players"], unique=False
    )
    op.create_index(
        op.f("idx_games_max_players"), "games", ["max_players"], unique=False
    )
    op.create_index(
        op.f("idx_games_family_games_rank"),
        "games",
        ["family_games_rank"],
        unique=False,
    )
    op.create_index(
        op.f("idx_games_childrens_games_rank"),
        "games",
        ["childrens_games_rank"],
        unique=False,
    )
    op.create_index(op.f("idx_games_cgs_rank"), "games", ["cgs_rank"], unique=False)
    op.create_index(
        op.f("idx_games_average_weight"), "games", ["average_weight"], unique=False
    )
    op.create_index(op.f("idx_games_average"), "games", ["average"], unique=False)
    op.create_index(
        op.f("idx_games_abstracts_rank"), "games", ["abstracts_rank"], unique=False
    )
    op.create_index(
        op.f("idx_designers_game_id"), "designers", ["game_id"], unique=False
    )
    op.create_index(
        op.f("idx_designers_boardgamedesigner_id"),
        "designers",
        ["boardgamedesigner_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_categories_game_id"), "categories", ["game_id"], unique=False
    )
    op.create_index(
        op.f("idx_categories_boardgamecategory_id"),
        "categories",
        ["boardgamecategory_id"],
        unique=False,
    )
    op.create_index(op.f("idx_artists_game_id"), "artists", ["game_id"], unique=False)
    op.create_index(
        op.f("idx_artists_boardgameartist_id"),
        "artists",
        ["boardgameartist_id"],
        unique=False,
    )
    # ### end Alembic commands ###
