"""Add composite performance indexes

Revision ID: 7091f7e4de89
Revises: 594a7422f114
Create Date: 2025-07-12 22:47:22.473125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7091f7e4de89'
down_revision: Union[str, None] = '594a7422f114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_categories_composite', 'categories', ['game_id', 'boardgamecategory_id'], unique=False)
    op.create_index('ix_games_player_range', 'games', ['min_players', 'max_players'], unique=False)
    op.create_index('ix_mechanics_composite', 'mechanics', ['game_id', 'boardgamemechanic_id'], unique=False)
    op.create_index('ix_suggested_players_composite', 'suggested_players', ['game_id', 'player_count', 'recommendation_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_suggested_players_composite', table_name='suggested_players')
    op.drop_index('ix_mechanics_composite', table_name='mechanics')
    op.drop_index('ix_games_player_range', table_name='games')
    op.drop_index('ix_categories_composite', table_name='categories')
    # ### end Alembic commands ###
