"""Remove email from users, add is_admin

Revision ID: ed8c617c6e84
Revises: 2ef6c56d7dc0
Create Date: 2025-06-24 12:28:22.548426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed8c617c6e84"
down_revision: Union[str, None] = "2ef6c56d7dc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return column_name in {
        column["name"] for column in inspector.get_columns(table_name)
    }


def index_exists(table_name: str, index_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return index_name in {index["name"] for index in inspector.get_indexes(table_name)}


def upgrade() -> None:
    """Upgrade schema."""
    if not column_exists("users", "is_admin"):
        op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))
    if index_exists("users", op.f("ix_users_email")):
        op.drop_index(op.f("ix_users_email"), table_name="users")
    if column_exists("users", "email"):
        op.drop_column("users", "email")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.VARCHAR(), nullable=True))
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=1)
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
